### ISSUE TITLE
I am havving trouble with the use of rocketmq-python in linux,python3.7

### ISSUE THREAD

**Issue by SoWhatI** [messense/rocketmq-python#22]
I am having trouble with the use of rocketmq-python in linux,python3.7,Details are as follows：

```
Traceback (most recent call last):
  File "./work.py", line 31, in <module>
    ret = producer.send_sync(msg)
  File "/usr/local/python37/lib/python3.7/site-packages/rocketmq/client.py", line 176, in send_sync
    ffi_check(dll.SendMessageSync(self._handle, msg, ctypes.pointer(cres)))
  File "/usr/local/python37/lib/python3.7/site-packages/rocketmq/exceptions.py", line 19, in ffi_check
    raise exc_cls()
rocketmq.exceptions.ProducerSendSyncFailed
```

```python
from rocketmq.client import Producer, Message
producer = Producer('group')
producer.set_namesrv_domain('192.168.1.1:9876')
# producer.set_session_credentials('XXX', 'XXXX', 'ALIYUN')
producer.start()
msg = Message('topic')
# msg.set_keys('XXX')
# msg.set_tags('XXX')
msg.set_body('XXXX')
ret = producer.send_sync(msg)
print(ret.status, ret.msg_id, ret.offset)
producer.shutdown()
```

**Comment by messense** [comment]
Try `producer. set_namesrv_addr('192.168.1.1:9876')` since you are not using Aliyun hosted rocketmq instance.

**Comment by SoWhatI** [comment]
> Try `producer.set_namesrv_addr('192.168.1.1:9876')` since you are not using Aliyun hosted rocketmq instance.

It worked.Thanks!
