### ISSUE TITLE
rocketmq.exceptions.ProducerSendSyncFailed

### ISSUE THREAD

**Issue by nishanthrk** [messense/rocketmq-python#23]
**ERROR MESSAGE**

```
Traceback (most recent call last):
  File "producer.py", line 14, in <module>
    ret = producer.send_sync(msg)
  File "/home/awok/Python/awok/lib/python3.7/site-packages/rocketmq/client.py", line 176, in send_sync
    ffi_check(dll.SendMessageSync(self._handle, msg, ctypes.pointer(cres)))
  File "/home/awok/Python/awok/lib/python3.7/site-packages/rocketmq/exceptions.py", line 19, in ffi_check
    raise exc_cls()
rocketmq.exceptions.ProducerSendSyncFailed
```

**PYTHON CODE**

```python
from rocketmq.client import Producer, Message

producer = Producer('PID-1235')
producer.set_namesrv_domain(
    'http://ons-me-east-1-internal.aliyuncs.com:8080/rocketmq/nsaddr4client-internal')
producer.set_session_credentials(
    'XXX', 'XXXX', 'ALIYUN')
producer.start()

msg = Message('test')
msg.set_keys('testing')
msg.set_tags('casdfas')
msg.set_body('hello')
ret = producer.send_sync(msg)
print(ret.status, ret.msg_id, ret.offset)
producer.shutdown()
```

@messense, please help me out in it

**Comment by messense** [comment]
Are you using Aliyun hosted RocketMQ service?

**Comment by nishanthrk** [comment]
> Are you using Aliyun hosted RocketMQ service?

Yeah

**Comment by messense** [comment]
Please check rocketmq-cpp logs under `~/logs/rocketmq-cpp` folder and paste relevant logs here.

**Comment by messense** [comment]
Close as inactive, feel free to reopen when you have more information to provide.
