### ISSUE TITLE
rocketmq.exceptions.ProducerSendSyncFailed ffi_check错误

### ISSUE THREAD

**Issue by billychou** [messense/rocketmq-python#29]
实例生产者代码中注释掉producer.set_session_credentials，其他都一样。报如下错误。
python 2.7， rocketmq 4.5
```
$python rocketmq_client_producer.py
Traceback (most recent call last):
  File "rocketmq_client_producer.py", line 15, in <module>
    ret = producer.send_sync(msg)
  File "/home/songchuan.zhou/env/py-env/lib/python2.7/site-packages/rocketmq/client.py", line 189, in send_sync
    ffi_check(dll.SendMessageSync(self._handle, msg, ctypes.pointer(cres)))
  File "/home/songchuan.zhou/env/py-env/lib/python2.7/site-packages/rocketmq/exceptions.py", line 19, in ffi_check
    raise exc_cls()
rocketmq.exceptions.ProducerSendSyncFailed
```

**Comment by messense** [comment]
贴一下 ~/logs/rocketmq-cpp 文件夹下面最新的日志。

**Comment by billychou** [comment]
```
[2019-Apr-24 10:42:47.753562](warning):Retry many times, still failed[sendDefaultImpl:374]
[2019-Apr-24 10:42:47.753615](error):msg: No route info of this topic: sanfendi_user_topic,error:-1,in file </tmp/rocketmq-client-cpp/src/producer/DefaultMQProducer.cpp> line:377[send:113]
```
从日志看没有创建topic，我手动创建一下topic试试。 谢谢

**Comment by billychou** [comment]
`./bin/mqadmin updateTopic -t "xxx" -c "DefaultCluster" -n localhost:xxx`  手动创建topic后解决。 谢谢

**Comment by messense** [comment]
ffi_check 4.0.1 版本之后会将错误信息附加到抛出的异常上

https://github.com/messense/rocketmq-python/commit/617d708c531fab70b465ca112fada058ba6f2458
