### ISSUE TITLE
消息发送

### ISSUE THREAD

**Issue by Ahrli** [messense/rocketmq-python#33]
Traceback (most recent call last):
  File "/Users/ahrli/Desktop/github/ce/1.py", line 15, in <module>
    ret = producer.send_sync(msg)
  File "/Users/ahrli/anaconda3/lib/python3.7/site-packages/rocketmq/client.py", line 189, in send_sync
    ffi_check(dll.SendMessageSync(self._handle, msg, ctypes.pointer(cres)))
  File "/Users/ahrli/anaconda3/lib/python3.7/site-packages/rocketmq/exceptions.py", line 19, in ffi_check
    raise exc_cls()
rocketmq.exceptions.ProducerSendSyncFailed

**Comment by messense** [comment]
贴一下 ~/logs/rocketmq-cpp 文件夹下面最新的日志。

参考 #29

**Comment by messense** [comment]
Close as inactive.
